import * as THREE from 'three';
import { AABB, boxFromCenter } from '../../core/collision';
import { Interactable } from '../../core/interact';
import { line } from '../../text/copy';
import { ActionState } from '../../core/types';
import { Chapter, GameContext } from '../../core/chapter';

const ROOM = { width: 10, depth: 10, height: 3 };
const WALL_THICKNESS = 0.4;

function surface(color: number): THREE.MeshLambertMaterial {
  return new THREE.MeshLambertMaterial({ color });
}

export interface TestRoom {
  group: THREE.Group;
  boxes: AABB[];
  interactables: Interactable[];
}

/**
 * A grey box with three props. Its only job is to prove every core system works
 * and holds framerate on a real phone before any real chapter is built.
 */
export function buildTestRoom(): TestRoom {
  const group = new THREE.Group();
  const boxes: AABB[] = [];
  const wallMat = surface(0x3a3d44);
  const floorMat = surface(0x2b2d33);

  const floor = new THREE.Mesh(
    new THREE.BoxGeometry(ROOM.width, WALL_THICKNESS, ROOM.depth),
    floorMat,
  );
  floor.position.set(0, -WALL_THICKNESS / 2, 0);
  group.add(floor);

  const halfW = ROOM.width / 2;
  const halfD = ROOM.depth / 2;
  const walls: Array<[number, number, number, number]> = [
    [0, -halfD, ROOM.width, WALL_THICKNESS],
    [0, halfD, ROOM.width, WALL_THICKNESS],
    [-halfW, 0, WALL_THICKNESS, ROOM.depth],
    [halfW, 0, WALL_THICKNESS, ROOM.depth],
  ];

  for (const [x, z, sx, sz] of walls) {
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(sx, ROOM.height, sz), wallMat);
    mesh.position.set(x, ROOM.height / 2, z);
    group.add(mesh);
    boxes.push(boxFromCenter(x, ROOM.height / 2, z, sx, ROOM.height, sz));
  }

  const props: Array<{
    id: string;
    position: [number, number, number];
    verbs: Interactable['verbs'];
    refuses?: Interactable['refuses'];
    solid: boolean;
  }> = [
    { id: 'test-crate', position: [2, 0.3, -2], verbs: ['look', 'take'], solid: false },
    { id: 'test-fixed', position: [-2, 0.3, -2], verbs: ['look', 'push'], solid: true },
    {
      id: 'test-refused',
      position: [0, 0.3, -3.5],
      verbs: ['look', 'take'],
      refuses: { take: line('test-refused', 0) ?? 'it stays.' },
      solid: false,
    },
  ];

  const interactables: Interactable[] = props.map((p) => {
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.6, 0.6, 0.6), surface(0x55585f));
    mesh.position.set(...p.position);
    mesh.name = p.id;
    group.add(mesh);
    if (p.solid) {
      boxes.push(boxFromCenter(p.position[0], p.position[1], p.position[2], 0.6, 0.6, 0.6));
    }
    return {
      id: p.id,
      object3D: mesh,
      verbs: p.verbs,
      refuses: p.refuses,
      onVerb: () => ({ handled: true, line: line(p.id, 0) }),
    };
  });

  return { group, boxes, interactables };
}

export class TestRoomChapter implements Chapter {
  readonly id = 0;
  private room: TestRoom | null = null;
  private ctx: GameContext | null = null;
  private carrying: string | null = null;

  async load(ctx: GameContext): Promise<void> {
    this.ctx = ctx;
    this.room = buildTestRoom();
    ctx.engine.scene.add(this.room.group);
    ctx.engine.setFog(0x05060a, 1, 18);
    for (const i of this.room.interactables) ctx.interactor.register(i);
    // A chapter owns its own spawn point and facing — ChapterRouter resets
    // to a documented default before this runs, but every chapter should
    // still set its own.
    ctx.player.reset([0, 0, 3], 0);

    // A chapter owns its own score. Two-layer grey test room proof: layer-a
    // is the reference (starts unlocked, gain 1), layer-b is silent until
    // the crate is taken (gain 0). Both WAVs (generated by
    // `npm run make-test-audio`) are exactly the same length, per
    // AudioDirector's hard requirement. ChapterRouter.load already cleared
    // any previous chapter's layers before calling here.
    const layerA = document.createElement('audio');
    layerA.src = '/audio/ch0/layer-a.wav';
    const layerB = document.createElement('audio');
    layerB.src = '/audio/ch0/layer-b.wav';
    ctx.audio.addLayer('layer-a', layerA, 1);
    ctx.audio.addLayer('layer-b', layerB, 0);
  }

  fixedUpdate(dtSeconds: number, actions: ActionState): void {
    const ctx = this.ctx;
    const room = this.room;
    if (!ctx || !room) return;

    // NOTE: this reads ctx.player.moving from the PREVIOUS frame, since the
    // lantern update runs before player.update below. That is a one-frame
    // lag on the idle timer (an idle->moving transition takes one extra
    // frame to reset the idle clock). Accepted: see Task 14 report.
    ctx.lantern.update(dtSeconds * 1000, ctx.player.moving, actions.holdToSee);
    ctx.player.update(dtSeconds, actions, room.boxes, ctx.lantern.frozen);
    // Order matters: player.applyTo must run before lantern.applyTo, or the
    // light trails the camera by a frame — visible on fast turns.
    ctx.player.applyTo(ctx.engine.camera);
    ctx.lantern.applyTo(ctx.engine.camera);

    const frame = ctx.interactor.update(
      ctx.engine.camera,
      actions,
      this.carrying !== null,
      dtSeconds * 1000,
    );

    // Debug room: never persist=true here — this is not real chapter
    // content, and doing so would permanently burn the game's one-ever `e`
    // prompt on a build nobody is meant to keep save state from.
    ctx.maybeShowInteractPrompt(frame.hovered, false);

    if (frame.result?.line) ctx.subtitle.show(frame.result.line);

    // Real progress, not "a verb fired": taking the crate is this room's
    // only objective, so it is the only thing that should reset the
    // anti-stuck clock. See the note on Chapter.fixedUpdate.
    let progressed = false;
    if (
      frame.fired === 'take' &&
      frame.result?.handled &&
      frame.hovered &&
      this.carrying === null
    ) {
      this.carrying = frame.hovered.id;
      ctx.audio.unlock('layer-b');
      progressed = true;
    }
    if (frame.fired === 'letGo') this.carrying = null;

    ctx.subtitle.update(dtSeconds * 1000);
    ctx.hint.update(dtSeconds * 1000, progressed);
    ctx.audio.update();
  }

  isComplete(): boolean {
    return this.carrying !== null;
  }

  root(): THREE.Object3D {
    return this.room?.group ?? new THREE.Group();
  }

  dispose(): void {
    if (this.room) {
      const materials = new Set<THREE.Material>();
      this.room.group.traverse((o) => {
        if (!(o instanceof THREE.Mesh)) return;
        o.geometry.dispose();
        const mats = Array.isArray(o.material) ? o.material : [o.material];
        for (const m of mats) materials.add(m);
      });
      for (const m of materials) m.dispose();
      this.room.group.removeFromParent();
    }
    this.room = null;
    this.ctx = null;
  }
}
