/**
 * Normalises a typed answer: lowercase, letters and single spaces only.
 * "I DON'T KNOW!!" and "i dont know" both land on the same string, so the
 * player is never punished for punctuation.
 *
 * Accented letters (e.g. "í") are stripped, not transliterated — a future
 * alias containing them would not behave as expected.
 */
export function normalizeAnswer(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/[^a-z\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Resolves `null` rather than throwing when `crypto.subtle` is unavailable —
 * notably plain-HTTP LAN testing, which is not a secure context. The gate
 * must never fail with an unhandled rejection; `checkAnswer` falls back to
 * `fnv1aHex` when this returns `null`.
 */
export async function sha256Hex(input: string): Promise<string | null> {
  try {
    const bytes = new TextEncoder().encode(input);
    const digest = await crypto.subtle.digest('SHA-256', bytes);
    return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
  } catch {
    // crypto.subtle is unavailable outside a secure context (plain-HTTP LAN
    // testing, old browsers). Never throw at the caller.
    return null;
  }
}

/**
 * Non-cryptographic fallback (FNV-1a, 32-bit), used only where crypto.subtle
 * is unavailable — notably plain-HTTP LAN testing, which is not a secure
 * context. The spec is explicit that this obfuscation only has to defeat
 * casual view-source; it is not and never was a security boundary.
 */
export function fnv1aHex(input: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
}

/**
 * Accepted answers, hashed. The spec calls for exactly one answer; this is an
 * array so an alias (e.g. "idk") is a one-line change if the drop-off ever
 * justifies it.
 *
 * Generated by scripts/answer-hash.mjs — do not edit by hand.
 */
export const ANSWER_HASHES: readonly string[] = [
  '1e5908a31683303df16f1ddeb8da9bc5cdf13af257d8cc854b1d5115dacc5c65',
];

/**
 * Fallback hashes (FNV-1a) for when crypto.subtle is unavailable.
 *
 * Generated by scripts/answer-hash.mjs — do not edit by hand.
 */
export const ANSWER_HASHES_FALLBACK: readonly string[] = ['9ea01c92'];

export async function checkAnswer(raw: string): Promise<boolean> {
  const normalized = normalizeAnswer(raw);
  if (!normalized) return false;
  const strong = await sha256Hex(normalized);
  if (strong !== null) return ANSWER_HASHES.includes(strong);
  return ANSWER_HASHES_FALLBACK.includes(fnv1aHex(normalized));
}

/**
 * The second word. Deliberately NOT hashed: it is a signpost, not a secret,
 * and the page refuses it outright until the answer has been solved, so
 * hiding it in a digest would protect nothing and cost readability.
 */
export const START_WORD = 'start';

export function isStartWord(raw: string): boolean {
  return normalizeAnswer(raw) === START_WORD;
}
